name: Build and Deploy to EC2

on:
  push:
    branches:
      - main
      - develop
      - 'release/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: war-artifact
          path: target/*.war

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy WAR to EC2
        run: |
          echo "Deploying to EC2..."
          ls -lh target/*.war
          sshpass -p "${{ secrets.EC2_PASSWORD }}" \
            scp -o StrictHostKeyChecking=no target/*.war \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/

# name: EC2 Deploy

# on:
#   push:
#     branches:
#       - 'features/**'
#       - develop
#       - release

# jobs:
#   deploy-dev:
#     if: startsWith(github.ref, 'refs/heads/features/')
#     uses: aruncena/devops-pipeline/.github/workflows/ec2.yaml@master
#     with:
#       environment: dev
#       app_name: my-app
#     secrets:
#       EC2_HOST: ${{ secrets.DEV_HOST }}
#       EC2_USER: ${{ secrets.EC2_USER }}
#       EC2_PASSWORD: ${{ secrets.EC2_PASSWORD }}

#   deploy-test-stage:
#     if: github.ref == 'refs/heads/develop'
#     strategy:
#       matrix:
#         env: [test, stage]
#     uses: aruncena/devops-pipeline/.github/workflows/ec2.yaml@master
#     with:
#       environment: ${{ matrix.env }}
#       app_name: my-app
#     secrets:
#       EC2_HOST: ${{ secrets[matrix.env == 'test' && 'TEST_HOST' || 'STAGE_HOST'] }}
#       EC2_USER: ${{ secrets.EC2_USER }}
#       EC2_PASSWORD: ${{ secrets.EC2_PASSWORD }}

#   deploy-prod:
#     if: github.ref == 'refs/heads/release'
#     uses: aruncena/devops-pipeline/.github/workflows/ec2.yaml@master
#     with:
#       environment: prod
#       app_name: my-app
#     secrets:
#       EC2_HOST: ${{ secrets.PROD_HOST }}
#       EC2_USER: ${{ secrets.EC2_USER }}
#       EC2_PASSWORD: ${{ secrets.EC2_PASSWORD }}


# name: EC2 deploy

# on:
#   push:
#     branches:
#       - 'features/**'
#       - develop
#       - release

# jobs:
#   deploy-dev:
#     if: startsWith(github.ref, 'refs/heads/features/')
#     uses: aruncena/devops-pipeline/.github/workflows/ec2.yaml@master
#     with:
#       environment: dev
#       app_name: my-app
#     secrets:
#       EC2_HOST: ${{ secrets.DEV_HOST }}
#       EC2_USER: ${{ secrets.EC2_USER }}
#       EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

#   deploy-test-stage:
#     if: github.ref == 'refs/heads/develop'
#     strategy:
#       matrix:
#         env: [test, stage]
#     uses: aruncena/devops-pipeline/.github/workflows/ec2.yaml@master
#     with:
#       environment: ${{ matrix.env }}
#       app_name: my-app
#     secrets:
#       EC2_HOST: ${{ secrets[matrix.env == 'test' && 'TEST_HOST' || 'STAGE_HOST'] }}
#       EC2_USER: ${{ secrets.EC2_USER }}
#       EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

#   deploy-prod:
#     if: github.ref == 'refs/heads/release'
#     uses: aruncena/devops-pipeline/.github/workflows/ec2.yaml@master
#     with:
#       environment: prod
#       app_name: my-app
#     secrets:
#       EC2_HOST: ${{ secrets.PROD_HOST }}
#       EC2_USER: ${{ secrets.EC2_USER }}
#       EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
